### ISSUE TITLE
Colourful Photo Database #1

### ISSUE THREAD

**Issue by AeishnaKhaund** [SEDSCelestiaBPGC/Externally-Randomized-Encryption-Service#1]
- take an image file and use OpenCV preprocessing tools to adjust the image dimensions to a square of a particular dimension (say N).

**Comment by AeishnaKhaund** [comment]
- convert the image to an array of values (dimensions N x N x 3)
> the 3rd dimension here represents the 3 colour channels: RGB

**Comment by AeishnaKhaund** [comment]
- divide the array into small subarrays (say width W). Then the final dimensions of these subarrays would be W x W x 3.

**Comment by AeishnaKhaund** [comment]
-  find average colour value for each subarray (that is, you average the values for each colour channel in a W x W array).

**Comment by nahush5** [comment]
>     * take an image file and use OpenCV preprocessing tools to adjust the image dimensions to a square of a particular dimension (say N).

Why is step necessary when we can directly do step 2 by using the resize function?

**Comment by gayatrip7** [comment]
If you can do it by the resize function, go ahead. It is meant to be open to whichever approach you wish to take. Would you like to take this issue up?

**Comment by nahush5** [comment]
Yes I would like to take up this issue, thanks!
Also I had few doubts on how the expected output sequence is. Since we are taking average, it comes out to be float. Is this to be converted to something else?

**Comment by gayatrip7** [comment]
It would be best if it was converted to int
