### ISSUE TITLE
White Noise Analysis #2

### ISSUE THREAD

**Issue by gayatrip7** [SEDSCelestiaBPGC/Externally-Randomized-Encryption-Service#10]
The code we had already created for this issue has become obsolete and we are moving it to a test branch. You may continue to work on it if you wish.

Take a .wav file of white noise, convert it into an array and isolate the amplitude, and convert the values to binary and store each digit into a one dimensional array.

**Comment by Goku2699** [comment]
What was the problem in the code? Was it not giving the output array?

**Comment by gayatrip7** [comment]
It was, but the output was becoming difficult to handle and decipher

**Comment by mujtaba1747** [comment]
I'm trying to figure out how to seperate the Amplitude.
But why are we seperating like this .... and why is it Amplitude...

**Comment by Goku2699** [comment]
Do you mean to remove silent parts of audio(isolate the amplitude)?

**Comment by gayatrip7** [comment]
No, the idea was to simply consider a characteristic of the sound independent of other information. Amplitude was an example, you can also take frequency if you wish
