### ISSUE TITLE
Rice and Stones #1

### ISSUE THREAD

**Issue by AeishnaKhaund** [SEDSCelestiaBPGC/Externally-Randomized-Encryption-Service#3]
- use OpenCV to adjust the dimensions of an image to square of a particular dimension.
>see #1 for reference

**Comment by AeishnaKhaund** [comment]
- convert the image to an array of numbers

**Comment by AeishnaKhaund** [comment]
- use OpenCV tools to threshold the colour values of the image to convert it to black and white.

**Comment by Goku2699** [comment]
How are we using 2nd step in 3rd step?

**Comment by Goku2699** [comment]
Also I'd like to take up this issue!!

**Comment by gayatrip7** [comment]
The idea was that arrays are relatively easy to manipulate

**Comment by Goku2699** [comment]
But using threshold function only the values of image are directly converted to make it black and white image.

**Comment by AeishnaKhaund** [comment]
@Goku2699 I dont see what the problem is. I think you're talking about the 'array of numbers' subtask. We simply meant you should use cv2.imread to load the images as arrays. Then you can use the threshold function to convert them. Is there still any confusion?
