### ISSUE TITLE
Colourful Photo Database #2

### ISSUE THREAD

**Issue by gayatrip7** [SEDSCelestiaBPGC/Externally-Randomized-Encryption-Service#9]
Use the array generated previously in this source. Assume X output arrays (from X different images) and select grid squares from each, randomly (you can use any random number generating library for this) and convert each value to binary. Store these binary values in a one dimensional array, digit by digit.

**Comment by nahush5** [comment]
I would like to take up this issue.
Also I don't understand what you mean by "select grid squares from each randomly" in the context of the precious code that was written. For X images the code would return an array of shape X x (W * W) x 3; so what do you mean by grid squares in these? Do you mean selecting a random set of 1 x 3 arrays from each of the X arrays ?

**Comment by gayatrip7** [comment]
we mean to select one random value from each array generated from an image.

**Comment by nahush5** [comment]
I am still not sure what you. Could you give an example for say the following output generated by the previous code.
Say the X x (W*W) x 3 array for X = 3 images and W = 2  is:
[
  [ [0.52, 0.28, 0.2], [0.1, 0.6, 0.3], [0.2, 0.3, 0.5], [0.4, 0.1, 0.5] ], 
  [ [0.2, 0.3, 0.5], [0.4, 0.1, 0.5], [0.52, 0.28, 0.2], [0.1, 0.6, 0.3] ], 
  [ [0.32, 0.64, 0.04], [0.25, 0.35, 0.4], [0.2, 0.3, 0.5], [0.4, 0.1, 0.5] ] 
].
Sorry for troubling, but i need to get this clarified to go ahead.

**Comment by gayatrip7** [comment]
select one tuple of 3 values (RGB) out of the array and take the average of them for each array
